name: run tests

on:
  push:
    branches:
      - latest
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  setup-node_modules:
    runs-on:
      - ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - uses: "nick-fields/retry@v2.9.0"
        with:
          max_attempts: 10
          timeout_minutes: 15
          retry_on: error
          command: pnpm fetch --ignore-scripts
  
  ci-tests:
    needs: setup-node_modules
    runs-on: 
      - ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        node-version: [18, 20]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: pnpm install
      uses: nick-fields/retry@v2.9.0
      with:
        max_attempts: 10
        timeout_minutes: 15
        retry_on: error
        command: pnpm install --frozen-lockfile
    - name: Run test suite
      run: pnpm test

  ci-build:
    needs: ci-tests
    runs-on: 
      - ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    - uses: pnpm/action-setup@v2.4.0
      with:
        version: 8
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
    - name: pnpm install
      uses: nick-fields/retry@v2.9.0
      with:
        max_attempts: 10
        timeout_minutes: 15
        retry_on: error
        command: pnpm install --frozen-lockfile
    - name: prebuild
      run:  |
        pnpm prebuild --v8_enable_pointer_compression=false --v8_enable_31bit_smis_on_64bit_arch=false
        tar --create --verbose --file=prebuild.tar --directory "prebuilds" .
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ runner.os }}
        path: prebuild.tar
